### ISSUE TITLE
Doesn't correctly graph system chaining

### ISSUE THREAD

**Issue by sdfgeoff** [jakobhellermann/bevy_mod_debugdump#4]
Only the outermost system is graphed, followed by some close brackets!
I think this is because to the scheduler they appear as one system?

**Comment by jakobhellermann** [comment]
That was a bug in my type name shortening code.
It now looks like this: 
![image](https://user-images.githubusercontent.com/22177966/111343096-6182e600-867b-11eb-847e-38c10b352da4.png)

**Comment by sdfgeoff** [comment]
Whew! That was fast. Nice job :)
