### ISSUE TITLE
Publish version supporting bevy 0.15

### ISSUE THREAD

**Issue by ActuallyHappening** [jakobhellermann/bevy_mod_debugdump#53]
Can we get a crates.io release supporting 0.15 please? This is a dependency of `bevy_editor_pls_default_windows` which I am trying to port to bevy 0.15

**Comment by jakobhellermann** [comment]
it's released now

**Comment by jakobhellermann** [comment]
> Can we get a crates.io release supporting 0.15 please? This is a dependency of bevy_editor_pls_default_windows which I am trying to port to bevy 0.15

Do you already start the porting and have some work locally? otherwise I'm was gonna update the crate now

**Comment by ActuallyHappening** [comment]
I was just `cargo tree`ing to investigate, no local changes yet
That would be greatly appreciated @jakobhellermann !
